[metadata]
name = "cosign"
description = "Container signing and verification"
homepage = "https://github.com/sigstore/cosign"
version_format = "semver"

[[steps]]
action = "github_file"
repo = "sigstore/cosign"
asset = "cosign-{os}-{arch}"
binaries = [{src = "cosign-{os}-{arch}", dest = "bin/cosign"}]

[verify]
command = "cosign version"
pattern = "{version}"
