[metadata]
name = "dasel"
description = "Query and modify data structures using selector strings"
homepage = "https://daseldocs.tomwright.me/"
version_format = "semver"

[[steps]]
action = "github_file"
repo = "TomWright/dasel"
asset_pattern = "dasel_{os}_{arch}"
binary = "dasel"

[verify]
# dasel includes v prefix in version output
command = "dasel --version"
pattern = "dasel version"
