[metadata]
name = "devspace"
description = "Developer tool for Kubernetes applications"
homepage = "https://devspace.sh/"
version_format = "semver"

[[steps]]
action = "github_file"
repo = "loft-sh/devspace"
asset = "devspace-{os}-{arch}"
binary = "devspace"

[verify]
command = "devspace version"
pattern = "DevSpace {version}"
