[metadata]
name = "netlify-cli"
description = "Netlify command line tool"
homepage = "https://www.netlify.com/products/cli/"
version_format = "semver"

[version]
source = "npm"
package = "netlify-cli"

[[steps]]
action = "npm_install"
package = "netlify-cli"
executables = ["netlify", "ntl"]

[verify]
command = "netlify --version"
pattern = "netlify-cli/"
