[metadata]
name = "jq"
description = "JSON processor"
homepage = "https://jqlang.github.io/jq/"
version_format = "semver"

[version]
github_repo = "jqlang/jq"
tag_prefix = "jq-"

[[steps]]
action = "github_file"
repo = "jqlang/jq"
asset_pattern = "jq-{os}-{arch}"
binary = "jq"

[verify]
command = "jq --version"
pattern = "jq-{version}"
