[metadata]
name = "goimports"
description = "Go import statement formatter"
homepage = "https://pkg.go.dev/golang.org/x/tools/cmd/goimports"
version_format = "semver"
dependencies = ["go"]

[version]
github_repo = "golang/tools"

[[steps]]
action = "go_install"
module = "golang.org/x/tools/cmd/goimports"
executables = ["goimports"]

[verify]
command = "goimports --help"
pattern = "goimports"
