[metadata]
name = "goimports"
description = "Go import statement formatter"
homepage = "https://pkg.go.dev/golang.org/x/tools/cmd/goimports"
dependencies = ["go"]

[version]
source = "goproxy"
module = "golang.org/x/tools"

[[steps]]
action = "go_install"
module = "golang.org/x/tools/cmd/goimports"
executables = ["goimports"]

[verify]
command = "goimports --help"
