[metadata]
name = "gore"
description = "Go REPL with line editing and completion"
homepage = "https://github.com/x-motemen/gore"
dependencies = ["go"]

[version]
source = "goproxy"
module = "github.com/x-motemen/gore"

[[steps]]
action = "go_install"
module = "github.com/x-motemen/gore/cmd/gore"
executables = ["gore"]

[verify]
command = "gore --help"
